// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SonicPulse.Infrastructure.Persistence;

#nullable disable

namespace SonicPulse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712200731_AddHotspotsAndGrouping")]
    partial class AddHotspotsAndGrouping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SonicPulse.Domain.Entities.Detection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<double>("GpsAccuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("gps_accuracy");

                    b.Property<Guid?>("HotspotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotspot_id");

                    b.Property<Point>("LocationPoint")
                        .HasColumnType("geography(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<double>("PeakDbfs")
                        .HasColumnType("double precision")
                        .HasColumnName("peak_dbfs");

                    b.Property<DateTime?>("PeakTimeClient")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("peak_time_client");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_status");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "SonicPulse.Domain.Entities.Detection.Location#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HotspotId");

                    b.HasIndex("LocationPoint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LocationPoint"), "gist");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.HasIndex("DeviceId", "SequenceNumber");

                    b.ToTable("detections", (string)null);
                });

            modelBuilder.Entity("SonicPulse.Domain.Entities.Hotspot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("device_count");

                    b.Property<DateTime>("FirstReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_received_at_utc");

                    b.Property<DateTime>("LastReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at_utc");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Centroid", "SonicPulse.Domain.Entities.Hotspot.Centroid#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centroid_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("centroid_longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LastReceivedAtUtc");

                    b.ToTable("hotspots", (string)null);
                });

            modelBuilder.Entity("SonicPulse.Domain.Entities.Detection", b =>
                {
                    b.HasOne("SonicPulse.Domain.Entities.Hotspot", null)
                        .WithMany()
                        .HasForeignKey("HotspotId");
                });
#pragma warning restore 612, 618
        }
    }
}
